[package]
name = "PreIPOPlatform"
version = "1.0.0"
authors = ["Invest360 Team"]

[addresses]
pre_ipo_platform = "0x277eb3eedde987fcef226bdee5409e2ec819da7e8ab305c8ce856eafa3a3dbc8"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "devnet", subdir = "aptos-move/framework/aptos-framework" }
